# Generated by Django 4.1.2 on 2022-11-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formfield",
            name="page",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="ContactPage",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
    ]
