# Generated by Django 4.1.2 on 2022-10-31 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('studio', '0002_aboutpage_aboutpagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagegalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image'),
        ),
    ]
