# Generated by Django 4.1.2 on 2022-11-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_contactpage_emailsnippet_emailorderables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailorderables",
            name="author",
        ),
        migrations.RemoveField(
            model_name="emailorderables",
            name="page",
        ),
        migrations.AddField(
            model_name="emailsnippet",
            name="IsActive",
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name="ContactPage",
        ),
        migrations.DeleteModel(
            name="EmailOrderables",
        ),
    ]
