# Generated by Django 4.1.2 on 2022-10-31 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('studio', '0008_alter_workpagegalleryimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpagegalleryimage',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnailimages', to='wagtailimages.image'),
        ),
    ]
