# Generated by Django 4.1.2 on 2022-10-31 10:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_alter_aboutpage_body_alter_workpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpage',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True),
        ),
    ]
