# Generated by Django 4.1.2 on 2022-10-31 11:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_alter_workpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True),
        ),
    ]
