# Generated by Django 4.1.2 on 2022-10-31 12:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('studio', '0012_alter_aboutpage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetailsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=250, null=True)),
                ('subtitle', models.CharField(max_length=250, null=True)),
                ('description', ckeditor.fields.RichTextField(max_length=5000, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='workpage',
            old_name='body',
            new_name='intro',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='subtitle',
        ),
        migrations.RenameModel(
            old_name='workPageGalleryImage',
            new_name='workDetailsPageGalleryImage',
        ),
        migrations.AlterField(
            model_name='workdetailspagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='studio.workdetailspage'),
        ),
    ]
