# Generated by Django 4.1.2 on 2022-11-01 04:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('studio', '0015_blogdetailspage_blogpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailspage',
            old_name='name',
            new_name='intro',
        ),
        migrations.RemoveField(
            model_name='blogdetailspage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogdetailspage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogdetailspage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='blogdetailspage',
            name='date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
        migrations.CreateModel(
            name='BlogPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='studio.blogdetailspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
