# Generated by Django 4.1.2 on 2022-11-01 05:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('studio', '0016_rename_name_blogdetailspage_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetailspagegalleryimage',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='workDetailsPagethumbnailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='studio.workdetailspage')),
                ('thumbnail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
