# Generated by Django 4.1.2 on 2022-11-07 04:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("studio", "0018_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="blogdetailspage",
            old_name="date",
            new_name="blog_date",
        ),
        migrations.RemoveField(
            model_name="blogdetailspage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="blogdetailspage",
            name="intro",
        ),
        migrations.AddField(
            model_name="blogdetailspage",
            name="blog_description",
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name="blogdetailspage",
            name="blog_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=ckeditor.fields.RichTextField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name="BlogPageGalleryImage",
        ),
        migrations.AddField(
            model_name="blogpageimage",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="studio.blogdetailspage",
            ),
        ),
    ]
